### PR TITLE
Clarify sortcom scope, align find/findcom keyword validation, and stabilize sort order for empty companies

### LINKED ISSUE #219: [PE-D][Tester A] `sortcom` - does not sort deleted list
Image

It is stated in the UserGuide that `sortcom` sorts the currently displayed list.
However, when I run `deleted` to display the deleted list, then run `sortcom`, CLInkedin sorts the non-deleted `list` instead.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #221: [PE-D][Tester A] `sortcom` - inconsistent INDEX for contacts without a company
### Initiation
On top of the default sample data provided, I first added the following:
- `add n/AAA p/11112222 e/AAA@example.com a/AAA Street`
- `add n/BBB p/11113333 e/BBB@example.com a/BBB Street`
- `add n/CCC p/11114444 e/CCC@example.com a/CCC Street`

After successfully adding these contacts without companies, I performed `sortcom`:
Image

### Bug
The command works as expected until we change any information about the contacts without companies. In this example screenshot, I entered:
`edit 3 r/CCC remark`

The position/index of the contacts without companies will jump around as shown: `CCC` changed from `3` to `2`
Image

- this can be recreated by changing any information about the person (i.e. not just adding remark)
- `tag assign` and `tag unassign` can also be used to recreate this bug
- this bug does not happen all the time

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #231: [PE-D][Tester A] `find` and `findcom` - behaviour mismatch
### `find`
Image

### `findcom`
Image

- should `findcom` accept malformed semicolon list?

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### LINKED ISSUE #237: [PE-D][Tester D] Sort company command fails on deleted list
Steps to reproduce:
- delete a few contacts i.e `delete 3`, `delete 2`, `delete 1`
- run the `deleted` command to view deleted list of contacts
- run `sortcom` 

Expected Behaviour:
- According to the UG: `Only the currently displayed list is sorted (e.g. after findcom or tag show)`, so I expected the deleted contact list to be sorted by company.

Actual Behaviour:
- The current list of contacts is sorted and shown instead of the deleted list.

After `deleted`:

Image.

After `sortcom`:

Image
Notice, for example, that Roy Balakrishnan is not in the deleted list

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by savagexr3**
**PR Description:**
This PR improves consistency between documentation and command behavior for `sortcom`, `find`, and `findcom`.

Changes made:

* Added a Planned Enhancement for supporting `sortcom` on the deleted list in future versions.
* Clarified documentation wording by replacing “currently displayed contact list” with “active contact list” for `sortcom`.
* Aligned `find` and `findcom` parsing behavior so malformed semicolon-separated inputs are consistently rejected, including cases like:

  * `[xxx];`
  * `;;;;;;`
  * `;[xxx]`
  * `;`
* Fixed handling of empty keywords in `find` and `findcom`, so commands like `find ;` and `findcom ;` now return an error instead of succeeding.
* Fixed inconsistent index changes in `sortcom` for contacts without a company by adding a deterministic tie-breaker using name.

Issues closed:

* closes #237
* closes #219
* closes #231
* closes #221

### CODE REVIEW

File: src/main/java/seedu/clinkedin/logic/commands/SortComCommand.java [hunk 1]
```diff
@@ -9,15 +9,15 @@
...
+ * Sorts the active contact list alphabetically by company name, case-insensitively.
+ * If no contacts are active, returns a message indicating that there is nothing to sort.
  */
 public class SortComCommand extends Command {
 
     public static final String COMMAND_WORD = "sortcom";
-    public static final String MESSAGE_EMPTY = "No contacts to be sorted by company name.";
-    public static final String MESSAGE_SUCCESS = "Contacts sorted by company name.";
-    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Sorts all displayed contacts by company name "
+    public static final String MESSAGE_EMPTY = "No active contacts to be sorted by company name.";
```
Comment (rxlee04) [inline src/main/java/seedu/clinkedin/logic/commands/SortComCommand.java]: Adding active in this part is a bit confusing.
it should be assumed is the active contact list unless otherwise mentioned?

File: src/main/java/seedu/clinkedin/model/ModelManager.java [hunk 2]
```diff
@@ -194,35 +194,44 @@ public void updateFilteredDeletedPersonRecordList(Predicate<DeletedPersonRecord>
...
+    //=========== Active Person List Sorting =============================================================
 
     /**
-     * Sorts the currently displayed (filtered) list of {@code Person} by company name (case-insensitive).
+     * Sorts the active list of {@code Person}
+     * by company name in a case-insensitive manner.
      *
      * <p>
-     * Sorting is applied only to the filtered view (i.e., {@code sortedPersons}),
+     * Sorting is applied only to the active view (i.e., {@code sortedPersons}),
```
Comment (rxlee04) [inline src/main/java/seedu/clinkedin/model/ModelManager.java]: should remain as filtered

File: src/main/java/seedu/clinkedin/logic/parser/FindCommandParser.java [hunk 3]
```diff
@@ -25,7 +25,7 @@ public FindCommand parse(String args) throws ParseException {
                     String.format(MESSAGE_INVALID_COMMAND_FORMAT, FindCommand.MESSAGE_USAGE));
         }
 
-        String[] nameKeywords = trimmedArgs.split(";");
+        String[] nameKeywords = trimmedArgs.split(";", -1);
```
Comment (rxlee04) [inline src/main/java/seedu/clinkedin/logic/parser/FindCommandParser.java]: @patrickstar1337 

please check if `find` is working the same way as before (jic)
(if no issue, comment & resolve comment)

Note: (I found one, unsure what is the expected result)
original: 
`find ;` output: `0 person listed`

new change:
`find ;` output: invalid command format

**Review by rxlee04 — CHANGES_REQUESTED** [review]

File: src/main/java/seedu/clinkedin/logic/parser/FindCommandParser.java (hunk 3 above)
Comment (patrickstar1337) [reply src/main/java/seedu/clinkedin/logic/parser/FindCommandParser.java]: It works fine, but I was used to ending my commands with a `;` (`find alex;`) which does not work now but I think it is intended.

May be a good idea to add in UG/DG and tell users not to end the command with a semi-colon?

@rxlee04 @savagexr3

Comment (rxlee04) [reply src/main/java/seedu/clinkedin/logic/parser/FindCommandParser.java]: I think this is a bit risky to change now.

`find ;` being invalid is okay since it is basically empty input, but rejecting `find alex;` might create a new bug or break existing behaviour since that was previously accepted. (to be honest is not uncommon for users to end with `;`)

Since PE did not flag this before, maybe safer to keep the old behaviour unless there is a strong reason to change it.

@patrickstar1337 @savagexr3

File: docs/UserGuide.md [hunk 4]
```diff
@@ -470,7 +470,7 @@ Action              | Format, Examples
 **Delete**          | `delete INDEX`<br> e.g., `delete 3`
 **Edit**            | `edit INDEX [n/NAME] [p/PHONE_NUMBER] [e/EMAIL] [a/ADDRESS] [c/COMPANY] [l/LINK] [r/REMARK] [t/TAG]…​`<br> e.g., `edit 2 n/James Lee e/jameslee@example.com`
 **Find**            | `find KEYWORD [MORE_KEYWORDS]`<br> e.g., `find James Jake`
-**Find Company**            | `findcom COMPANY [; MORE_COMPANY]`<br> e.g., `find Google; Amazon`
+**Find Company**            | `findcom KEYWORD [MORE_KEYWORDS]`<br> e.g., `find Google; Amazon`
```
Comment (rxlee04) [inline docs/UserGuide.md]: missing `;`

**Review by rxlee04 — CHANGES_REQUESTED** [review]
only one more change needed, then everything else is okay

**Review by rxlee04 — APPROVED** [review]
LGTM!
